language: node_js
node_js:
  - 6.9.1
services:
  - mysql
before_install:
  - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
  - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
  - sudo DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.1-1_all.deb
  - sudo apt-get update -q
  - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
  - sudo mysql_upgrade
  - mysql -e 'CREATE DATABASE quizwiz_travis_db'
script:
  - npm run travis-test
  - echo $NODE_ENV
dist: trusty
sudo: required